name: Run Renovate
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * 6' # weekly; 08:00 at Saturday

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Octo STS Token Exchange
        uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec # v1.0.3
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: renovate

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@c91a61c730fa166439cd3e2c300c041590002b1d # v44.0.3
        with:
          configurationFile: ./.github/renovate.json5
          token: ${{ steps.octo-sts.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM: "github"
          LOG_LEVEL: "debug"
